# Используем официальный образ Python 3.12
FROM python:3.12

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем все файлы из текущей директории в /app контейнера
COPY . .

# Устанавливаем библиотеку redis
RUN pip install redis

# Команда, которая выполняется при запуске контейнера
CMD ["python", "docker_compose_example.py"]